name: Build
on:
  pull_request:
    types: [opened, reopened, synchronize]
jobs:
  build-projects:
    name: Build All Projects
    runs-on: windows-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Build
        run: dotnet build -c Release
